### ISSUE TITLE
Veillet Chemistry Photonetwork not converging.

### ISSUE THREAD

**Issue by ahmed-f-alrefaie** [ahmed-f-alrefaie/freckll#5]
@oliviavenot 
@Shiuay 

I have has some success with integrating fully the Veillet chemistry network.

For thermochemistry the values are:

```yaml
thermochemistry:
  format: ace
  abundances: [12.0, 10.925, 9.168, 7.86, 8.633, 3.21]
  elements: [H, He, C, N, O, S]
```

If photochemistry is excluded it takes roughly ~70 seconds to converge to steady state at $10^{10}$

https://github.com/user-attachments/assets/8ade4666-05e4-4ecc-849c-efe0a0d2b3d2

However when photochemistry is included it becomes unstable and looks like it converges early before growing unstable.. @Shiuay in your previous use of FRECKLL was the photochemical scheme for this network ever an issue?

Here is the failed solution

https://github.com/user-attachments/assets/e0c82733-2414-4d13-a197-e0a9e1c7b2f8
