### ISSUE TITLE
Advection term

### ISSUE THREAD

**Issue by ahmed-f-alrefaie** [ahmed-f-alrefaie/freckll#6]
Advection term:

$
D n_i (\frac{H})
$

Needs to implement a more stable scheme.

**Comment by ahmed-f-alrefaie** [comment]
As suggested by [Nicholaswogan](https://github.com/Nicholaswogan) the upwind scheme does make the advection term significantly more stable and solvable.

I've included an ``use_upwind`` lever in the input file:

```yaml
solver:
  method: rosenbrock
  t_span: [0.0, 1e12]
  nevals: 200
  dn_crit: 1e-3
  dndt_crit: 1e-6
  max_solve_time: 1 hour
  enable_diffusion: true
  use_upwind: true
```
